# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       qmlmusicplayer

# >> macros
# << macros

Summary:    Nemo Mobile Music Player
Version:    2.0.1
Release:    1
Group:      Applications/Multimedia
License:    GPLv2
URL:        https://github.com/nemomobile/qmlmusicplayer
Source0:    %{name}-%{version}.tar.bz2
Source100:  qmlmusicplayer.yaml
Requires:   mapplauncherd-booster-qtcomponents-qt5
Requires:   qt-components-qt5
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  pkgconfig(Qt5OpenGL)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  pkgconfig(qdeclarative5-boostable)
BuildRequires:  desktop-file-utils
Provides:   org.pycage.musicshelf > 1.0.1
Obsoletes:   org.pycage.musicshelf <= 1.0.1

%description
Music Player for Nemo Mobile

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
# >> files
/opt/qmlmediaplayer/bin/qmlmediaplayer
%{_datadir}/applications/qmlmediaplayer.desktop
%{_datadir}/pixmaps/qmlmediaplayer.png
# << files
